// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, payment_method, currency, initial_balance, initial_date, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, payment_method, currency, initial_balance, initial_date, is_active, notes, created_at, updated_at
`

type CreateAccountParams struct {
	Name           string
	PaymentMethod  pgtype.Text
	Currency       string
	InitialBalance pgtype.Numeric
	InitialDate    pgtype.Date
	Notes          pgtype.Text
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.PaymentMethod,
		arg.Currency,
		arg.InitialBalance,
		arg.InitialDate,
		arg.Notes,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentMethod,
		&i.Currency,
		&i.InitialBalance,
		&i.InitialDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE accounts SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, payment_method, currency, initial_balance, initial_date, is_active, notes, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentMethod,
		&i.Currency,
		&i.InitialBalance,
		&i.InitialDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountExpenses = `-- name: GetAccountExpenses :one
SELECT COALESCE(SUM(
    CASE
        WHEN charged_currency = $2 AND charged_amount IS NOT NULL THEN charged_amount
        ELSE amount
    END
), 0)::numeric AS total
FROM expenses
WHERE account_id   = $1
  AND date         >= $3
  AND transfer_id  IS NULL
  AND (currency = $2 OR charged_currency = $2)
`

type GetAccountExpensesParams struct {
	AccountID       pgtype.UUID
	ChargedCurrency pgtype.Text
	Date            pgtype.Timestamptz
}

// Sums expenses for an account since initialDate.
// Excludes transfer fees (transfer_id IS NOT NULL) — already included in fromAmount.
// Uses chargedAmount when currency differs from account currency.
func (q *Queries) GetAccountExpenses(ctx context.Context, arg GetAccountExpensesParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountExpenses, arg.AccountID, arg.ChargedCurrency, arg.Date)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getAccountTransfersIn = `-- name: GetAccountTransfersIn :one
SELECT COALESCE(SUM(to_amount), 0)::numeric AS total
FROM transfers
WHERE to_account_id = $1
  AND date >= $2
`

type GetAccountTransfersInParams struct {
	ToAccountID pgtype.UUID
	Date        pgtype.Timestamptz
}

func (q *Queries) GetAccountTransfersIn(ctx context.Context, arg GetAccountTransfersInParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountTransfersIn, arg.ToAccountID, arg.Date)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getAccountTransfersOut = `-- name: GetAccountTransfersOut :one
SELECT COALESCE(SUM(from_amount), 0)::numeric AS total
FROM transfers
WHERE from_account_id = $1
  AND date >= $2
`

type GetAccountTransfersOutParams struct {
	FromAccountID pgtype.UUID
	Date          pgtype.Timestamptz
}

func (q *Queries) GetAccountTransfersOut(ctx context.Context, arg GetAccountTransfersOutParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountTransfersOut, arg.FromAccountID, arg.Date)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const listActiveAccounts = `-- name: ListActiveAccounts :many
SELECT id, name, payment_method, currency, initial_balance, initial_date, is_active, notes, created_at, updated_at FROM accounts WHERE is_active = true ORDER BY created_at
`

func (q *Queries) ListActiveAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listActiveAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PaymentMethod,
			&i.Currency,
			&i.InitialBalance,
			&i.InitialDate,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name            = COALESCE($1, name),
    initial_balance = COALESCE($2, initial_balance),
    initial_date    = COALESCE($3, initial_date),
    notes           = COALESCE($4, notes),
    updated_at      = NOW()
WHERE id = $5
RETURNING id, name, payment_method, currency, initial_balance, initial_date, is_active, notes, created_at, updated_at
`

type UpdateAccountParams struct {
	Name           pgtype.Text
	InitialBalance pgtype.Numeric
	InitialDate    pgtype.Date
	Notes          pgtype.Text
	ID             pgtype.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.InitialBalance,
		arg.InitialDate,
		arg.Notes,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PaymentMethod,
		&i.Currency,
		&i.InitialBalance,
		&i.InitialDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
