// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, date, amount, currency, charged_amount, charged_currency,
                      account_id, category_id, description, transfer_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, transfer_id, created_at, updated_at
`

type CreateExpenseParams struct {
	UserID          pgtype.UUID
	Date            pgtype.Timestamptz
	Amount          pgtype.Numeric
	Currency        string
	ChargedAmount   pgtype.Numeric
	ChargedCurrency pgtype.Text
	AccountID       pgtype.UUID
	CategoryID      pgtype.UUID
	Description     pgtype.Text
	TransferID      pgtype.UUID
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.Date,
		arg.Amount,
		arg.Currency,
		arg.ChargedAmount,
		arg.ChargedCurrency,
		arg.AccountID,
		arg.CategoryID,
		arg.Description,
		arg.TransferID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.ChargedAmount,
		&i.ChargedCurrency,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.TransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, transfer_id, created_at, updated_at FROM expenses ORDER BY date DESC
`

func (q *Queries) ListExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.TransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByAccount = `-- name: ListExpensesByAccount :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, transfer_id, created_at, updated_at FROM expenses
WHERE account_id = $1
ORDER BY date DESC
`

func (q *Queries) ListExpensesByAccount(ctx context.Context, accountID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.TransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByDateRange = `-- name: ListExpensesByDateRange :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, transfer_id, created_at, updated_at FROM expenses
WHERE date >= $1 AND date < $2
ORDER BY date DESC
`

type ListExpensesByDateRangeParams struct {
	Date   pgtype.Timestamptz
	Date_2 pgtype.Timestamptz
}

func (q *Queries) ListExpensesByDateRange(ctx context.Context, arg ListExpensesByDateRangeParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.TransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, transfer_id, created_at, updated_at FROM expenses WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListExpensesByUser(ctx context.Context, userID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.TransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET amount           = COALESCE($1, amount),
    currency         = COALESCE($2, currency),
    charged_amount   = COALESCE($3, charged_amount),
    charged_currency = COALESCE($4, charged_currency),
    description      = COALESCE($5, description),
    category_id      = COALESCE($6, category_id),
    date             = COALESCE($7, date),
    updated_at       = NOW()
WHERE id = $8
RETURNING id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, transfer_id, created_at, updated_at
`

type UpdateExpenseParams struct {
	Amount          pgtype.Numeric
	Currency        pgtype.Text
	ChargedAmount   pgtype.Numeric
	ChargedCurrency pgtype.Text
	Description     pgtype.Text
	CategoryID      pgtype.UUID
	Date            pgtype.Timestamptz
	ID              pgtype.UUID
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.Amount,
		arg.Currency,
		arg.ChargedAmount,
		arg.ChargedCurrency,
		arg.Description,
		arg.CategoryID,
		arg.Date,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.ChargedAmount,
		&i.ChargedCurrency,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.TransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
