// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: income.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncome = `-- name: CreateIncome :one
INSERT INTO incomes (user_id, date, amount, currency, charged_amount, charged_currency,
                     account_id, category_id, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, created_at, updated_at
`

type CreateIncomeParams struct {
	UserID          pgtype.UUID
	Date            pgtype.Timestamptz
	Amount          pgtype.Numeric
	Currency        string
	ChargedAmount   pgtype.Numeric
	ChargedCurrency pgtype.Text
	AccountID       pgtype.UUID
	CategoryID      pgtype.UUID
	Description     pgtype.Text
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.UserID,
		arg.Date,
		arg.Amount,
		arg.Currency,
		arg.ChargedAmount,
		arg.ChargedCurrency,
		arg.AccountID,
		arg.CategoryID,
		arg.Description,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.ChargedAmount,
		&i.ChargedCurrency,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM incomes WHERE id = $1
`

func (q *Queries) DeleteIncome(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncome, id)
	return err
}

const listIncomes = `-- name: ListIncomes :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, created_at, updated_at FROM incomes ORDER BY date DESC
`

func (q *Queries) ListIncomes(ctx context.Context) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByDateRange = `-- name: ListIncomesByDateRange :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, created_at, updated_at FROM incomes
WHERE date >= $1 AND date < $2
ORDER BY date DESC
`

type ListIncomesByDateRangeParams struct {
	Date   pgtype.Timestamptz
	Date_2 pgtype.Timestamptz
}

func (q *Queries) ListIncomesByDateRange(ctx context.Context, arg ListIncomesByDateRangeParams) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomesByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByUser = `-- name: ListIncomesByUser :many
SELECT id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, created_at, updated_at FROM incomes WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) ListIncomesByUser(ctx context.Context, userID pgtype.UUID) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.ChargedAmount,
			&i.ChargedCurrency,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE incomes
SET amount           = COALESCE($1, amount),
    currency         = COALESCE($2, currency),
    charged_amount   = COALESCE($3, charged_amount),
    charged_currency = COALESCE($4, charged_currency),
    description      = COALESCE($5, description),
    category_id      = COALESCE($6, category_id),
    date             = COALESCE($7, date),
    updated_at       = NOW()
WHERE id = $8
RETURNING id, user_id, date, amount, currency, charged_amount, charged_currency, account_id, category_id, description, created_at, updated_at
`

type UpdateIncomeParams struct {
	Amount          pgtype.Numeric
	Currency        pgtype.Text
	ChargedAmount   pgtype.Numeric
	ChargedCurrency pgtype.Text
	Description     pgtype.Text
	CategoryID      pgtype.UUID
	Date            pgtype.Timestamptz
	ID              pgtype.UUID
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.Amount,
		arg.Currency,
		arg.ChargedAmount,
		arg.ChargedCurrency,
		arg.Description,
		arg.CategoryID,
		arg.Date,
		arg.ID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.ChargedAmount,
		&i.ChargedCurrency,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
