// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLot = `-- name: CreateLot :one
INSERT INTO account_lots (account_id, transfer_id, original_amount, rate_to_base, remaining, base_currency, date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, transfer_id, original_amount, rate_to_base, remaining, base_currency, date, created_at
`

type CreateLotParams struct {
	AccountID      pgtype.UUID
	TransferID     pgtype.UUID
	OriginalAmount pgtype.Numeric
	RateToBase     pgtype.Numeric
	Remaining      pgtype.Numeric
	BaseCurrency   string
	Date           pgtype.Timestamptz
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (AccountLot, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.AccountID,
		arg.TransferID,
		arg.OriginalAmount,
		arg.RateToBase,
		arg.Remaining,
		arg.BaseCurrency,
		arg.Date,
	)
	var i AccountLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.OriginalAmount,
		&i.RateToBase,
		&i.Remaining,
		&i.BaseCurrency,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const listAvailableLots = `-- name: ListAvailableLots :many
SELECT id, account_id, transfer_id, original_amount, rate_to_base, remaining, base_currency, date, created_at FROM account_lots
WHERE account_id = $1 AND remaining > 0
ORDER BY date ASC, created_at ASC
`

func (q *Queries) ListAvailableLots(ctx context.Context, accountID pgtype.UUID) ([]AccountLot, error) {
	rows, err := q.db.Query(ctx, listAvailableLots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountLot
	for rows.Next() {
		var i AccountLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransferID,
			&i.OriginalAmount,
			&i.RateToBase,
			&i.Remaining,
			&i.BaseCurrency,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLotRemaining = `-- name: UpdateLotRemaining :one
UPDATE account_lots
SET remaining = $2
WHERE id = $1
RETURNING id, account_id, transfer_id, original_amount, rate_to_base, remaining, base_currency, date, created_at
`

type UpdateLotRemainingParams struct {
	ID        pgtype.UUID
	Remaining pgtype.Numeric
}

func (q *Queries) UpdateLotRemaining(ctx context.Context, arg UpdateLotRemainingParams) (AccountLot, error) {
	row := q.db.QueryRow(ctx, updateLotRemaining, arg.ID, arg.Remaining)
	var i AccountLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransferID,
		&i.OriginalAmount,
		&i.RateToBase,
		&i.Remaining,
		&i.BaseCurrency,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}
