// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Name           string
	PaymentMethod  pgtype.Text
	Currency       string
	InitialBalance pgtype.Numeric
	InitialDate    pgtype.Date
	IsActive       bool
	Notes          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Category struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	ParentID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Currency struct {
	Code      string
	Name      string
	Symbol    string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type Expense struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Date            pgtype.Timestamptz
	Amount          pgtype.Numeric
	Currency        string
	ChargedAmount   pgtype.Numeric
	ChargedCurrency pgtype.Text
	AccountID       pgtype.UUID
	CategoryID      pgtype.UUID
	Description     pgtype.Text
	TransferID      pgtype.UUID
	IsRefund        bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Income struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Date              pgtype.Timestamptz
	Amount            pgtype.Numeric
	Currency          string
	ChargedAmount     pgtype.Numeric
	ChargedCurrency   pgtype.Text
	AccountID         pgtype.UUID
	CategoryID        pgtype.UUID
	Description       pgtype.Text
	IsRefund          bool
	RefundedExpenseID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Transfer struct {
	ID                  pgtype.UUID
	Date                pgtype.Timestamptz
	FromAccountID       pgtype.UUID
	FromAmount          pgtype.Numeric
	FromCurrency        pgtype.Text
	ToAccountID         pgtype.UUID
	ToAmount            pgtype.Numeric
	ToCurrency          string
	Commission          pgtype.Numeric
	CommissionCurrency  pgtype.Text
	Commission2         pgtype.Numeric
	Commission2Currency pgtype.Text
	Description         pgtype.Text
	LinkedTransferID    pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}
