// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllTimeMonthlyStats = `-- name: GetAllTimeMonthlyStats :many
SELECT
  EXTRACT(YEAR  FROM date)::int          AS year,
  EXTRACT(MONTH FROM date)::int          AS month,
  COUNT(*)::int                          AS count,
  COALESCE(SUM(base_amount), 0)::numeric AS total
FROM expenses
WHERE base_currency = $1
  AND ($2::uuid IS NULL OR user_id = $2::uuid)
  AND is_refund = false
  AND base_amount IS NOT NULL
GROUP BY year, month
ORDER BY year, month
`

type GetAllTimeMonthlyStatsParams struct {
	BaseCurrency pgtype.Text
	UserID       pgtype.UUID
}

type GetAllTimeMonthlyStatsRow struct {
	Year  int32
	Month int32
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) GetAllTimeMonthlyStats(ctx context.Context, arg GetAllTimeMonthlyStatsParams) ([]GetAllTimeMonthlyStatsRow, error) {
	rows, err := q.db.Query(ctx, getAllTimeMonthlyStats, arg.BaseCurrency, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTimeMonthlyStatsRow
	for rows.Next() {
		var i GetAllTimeMonthlyStatsRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Count,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthStats = `-- name: GetMonthStats :one
SELECT
  COUNT(*)::int                          AS count,
  COALESCE(SUM(base_amount), 0)::numeric AS total
FROM expenses
WHERE base_currency = $1
  AND date >= $2
  AND date < $3
  AND ($4::uuid IS NULL OR user_id = $4::uuid)
  AND is_refund = false
`

type GetMonthStatsParams struct {
	BaseCurrency pgtype.Text
	Date         pgtype.Timestamptz
	Date_2       pgtype.Timestamptz
	UserID       pgtype.UUID
}

type GetMonthStatsRow struct {
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) GetMonthStats(ctx context.Context, arg GetMonthStatsParams) (GetMonthStatsRow, error) {
	row := q.db.QueryRow(ctx, getMonthStats,
		arg.BaseCurrency,
		arg.Date,
		arg.Date_2,
		arg.UserID,
	)
	var i GetMonthStatsRow
	err := row.Scan(&i.Count, &i.Total)
	return i, err
}

const getMonthStatsByYear = `-- name: GetMonthStatsByYear :many
SELECT
  EXTRACT(MONTH FROM date)::int          AS month,
  COUNT(*)::int                          AS count,
  COALESCE(SUM(base_amount), 0)::numeric AS total
FROM expenses
WHERE base_currency = $1
  AND date >= $2
  AND date < $3
  AND ($4::uuid IS NULL OR user_id = $4::uuid)
  AND is_refund = false
  AND base_amount IS NOT NULL
GROUP BY EXTRACT(MONTH FROM date)
ORDER BY month
`

type GetMonthStatsByYearParams struct {
	BaseCurrency pgtype.Text
	Date         pgtype.Timestamptz
	Date_2       pgtype.Timestamptz
	UserID       pgtype.UUID
}

type GetMonthStatsByYearRow struct {
	Month int32
	Count int32
	Total pgtype.Numeric
}

func (q *Queries) GetMonthStatsByYear(ctx context.Context, arg GetMonthStatsByYearParams) ([]GetMonthStatsByYearRow, error) {
	rows, err := q.db.Query(ctx, getMonthStatsByYear,
		arg.BaseCurrency,
		arg.Date,
		arg.Date_2,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthStatsByYearRow
	for rows.Next() {
		var i GetMonthStatsByYearRow
		if err := rows.Scan(&i.Month, &i.Count, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
