// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (date, from_account_id, from_amount, from_currency,
                       to_account_id, to_amount, to_currency,
                       commission, commission_currency,
                       commission2, commission2_currency,
                       description, linked_transfer_id, rate)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, date, from_account_id, from_amount, from_currency, to_account_id, to_amount, to_currency, commission, commission_currency, commission2, commission2_currency, description, rate, linked_transfer_id, created_at, updated_at
`

type CreateTransferParams struct {
	Date                pgtype.Timestamptz
	FromAccountID       pgtype.UUID
	FromAmount          pgtype.Numeric
	FromCurrency        pgtype.Text
	ToAccountID         pgtype.UUID
	ToAmount            pgtype.Numeric
	ToCurrency          string
	Commission          pgtype.Numeric
	CommissionCurrency  pgtype.Text
	Commission2         pgtype.Numeric
	Commission2Currency pgtype.Text
	Description         pgtype.Text
	LinkedTransferID    pgtype.UUID
	Rate                pgtype.Numeric
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.Date,
		arg.FromAccountID,
		arg.FromAmount,
		arg.FromCurrency,
		arg.ToAccountID,
		arg.ToAmount,
		arg.ToCurrency,
		arg.Commission,
		arg.CommissionCurrency,
		arg.Commission2,
		arg.Commission2Currency,
		arg.Description,
		arg.LinkedTransferID,
		arg.Rate,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.FromAccountID,
		&i.FromAmount,
		&i.FromCurrency,
		&i.ToAccountID,
		&i.ToAmount,
		&i.ToCurrency,
		&i.Commission,
		&i.CommissionCurrency,
		&i.Commission2,
		&i.Commission2Currency,
		&i.Description,
		&i.Rate,
		&i.LinkedTransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers WHERE id = $1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransfer, id)
	return err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, date, from_account_id, from_amount, from_currency, to_account_id, to_amount, to_currency, commission, commission_currency, commission2, commission2_currency, description, rate, linked_transfer_id, created_at, updated_at FROM transfers WHERE id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, id pgtype.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.FromAccountID,
		&i.FromAmount,
		&i.FromCurrency,
		&i.ToAccountID,
		&i.ToAmount,
		&i.ToCurrency,
		&i.Commission,
		&i.CommissionCurrency,
		&i.Commission2,
		&i.Commission2Currency,
		&i.Description,
		&i.Rate,
		&i.LinkedTransferID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, date, from_account_id, from_amount, from_currency, to_account_id, to_amount, to_currency, commission, commission_currency, commission2, commission2_currency, description, rate, linked_transfer_id, created_at, updated_at FROM transfers ORDER BY date DESC
`

func (q *Queries) ListTransfers(ctx context.Context) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.FromAccountID,
			&i.FromAmount,
			&i.FromCurrency,
			&i.ToAccountID,
			&i.ToAmount,
			&i.ToCurrency,
			&i.Commission,
			&i.CommissionCurrency,
			&i.Commission2,
			&i.Commission2Currency,
			&i.Description,
			&i.Rate,
			&i.LinkedTransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByAccount = `-- name: ListTransfersByAccount :many
SELECT id, date, from_account_id, from_amount, from_currency, to_account_id, to_amount, to_currency, commission, commission_currency, commission2, commission2_currency, description, rate, linked_transfer_id, created_at, updated_at FROM transfers
WHERE (from_account_id = $1 OR to_account_id = $1)
  AND ($2::timestamptz IS NULL OR date >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR date < $3::timestamptz)
ORDER BY date DESC
`

type ListTransfersByAccountParams struct {
	AccountID pgtype.UUID
	DateFrom  pgtype.Timestamptz
	DateTo    pgtype.Timestamptz
}

func (q *Queries) ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByAccount, arg.AccountID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.FromAccountID,
			&i.FromAmount,
			&i.FromCurrency,
			&i.ToAccountID,
			&i.ToAmount,
			&i.ToCurrency,
			&i.Commission,
			&i.CommissionCurrency,
			&i.Commission2,
			&i.Commission2Currency,
			&i.Description,
			&i.Rate,
			&i.LinkedTransferID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
